/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef comsumer_CONSTANTS_H
#define comsumer_CONSTANTS_H

#include "comsumer_types.h"

namespace essential { namespace consumer {

class comsumerConstants {
 public:
  comsumerConstants();

};

extern const comsumerConstants g_comsumer_constants;

}} // namespace

#endif
