/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef login_CONSTANTS_H
#define login_CONSTANTS_H

#include "login_types.h"

namespace essential { namespace login {

class loginConstants {
 public:
  loginConstants();

};

extern const loginConstants g_login_constants;

}} // namespace

#endif
