/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "login_constants.h"

namespace essential { namespace login {

const loginConstants g_login_constants;

loginConstants::loginConstants() {
}

}} // namespace

