/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef provider_CONSTANTS_H
#define provider_CONSTANTS_H

#include "provider_types.h"

namespace essential { namespace provider {

class providerConstants {
 public:
  providerConstants();

};

extern const providerConstants g_provider_constants;

}} // namespace

#endif
