/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "provider_constants.h"

namespace essential { namespace provider {

const providerConstants g_provider_constants;

providerConstants::providerConstants() {
}

}} // namespace

